### ISSUE TITLE
getGuildMembers always returns 1 member regardless of limit

### ISSUE THREAD

**Issue by gomander** [DasWolke/SnowTransfer#40]
```
const client = new SnowTransfer(process.env.TOKEN)
const members = await client.guild.getGuildMembers(guildId, { limit: 10 })
```

`members` will always be an array with only 1 GuildMember regardless of what the limit is set to.

I made the request myself using fetch:
```
const headers = new Headers()
headers.set('Authorization', 'Bot ' + process.env.TOKEN!)
const response = await fetch(
  `https://discord.com/api/v10/guilds/${guildId}/members?limit=10`,
  { headers }
)
const members = await response.json()
```
Here `members` is an array with 10 GuildMembers.

I have made sure that `process.env.TOKEN` and `guildId` are correct, and the bot has the `GUILD_MEMBERS` intent enabled.

**Comment by PapiOphidian** [comment]
I found the issue. I'll fix this next chance I get - likely later today or tomorrow.
